package profiles

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strings"
	"testing"

	"github.com/google/pprof/profile"
	"github.com/greatliontech/gofresh"
	"github.com/greatliontech/pew/internal/recordingtest"
	"github.com/greatliontech/pew/internal/run"
	"github.com/greatliontech/pew/internal/store"
)

func encodedProfile(t testing.TB, values ...int64) []byte {
	t.Helper()
	f := &profile.Function{ID: 1, Name: "example.com/p.Work", Filename: "/src/work.go", StartLine: 2}
	l := &profile.Location{ID: 1, Line: []profile.Line{{Function: f, Line: 3}}}
	p := &profile.Profile{SampleType: []*profile.ValueType{{Type: "cpu", Unit: "nanoseconds"}}, Function: []*profile.Function{f}, Location: []*profile.Location{l}, PeriodType: &profile.ValueType{Type: "cpu", Unit: "nanoseconds"}, Period: 10000000}
	for i, value := range values {
		s := &profile.Sample{Value: []int64{value}}
		if i%2 == 0 {
			s.Location = []*profile.Location{l}
		}
		p.Sample = append(p.Sample, s)
	}
	var b bytes.Buffer
	if err := p.Write(&b); err != nil {
		t.Fatal(err)
	}
	return b.Bytes()
}

func TestFlatWeightsConserveUnresolvedSamples(t *testing.T) {
	src := Source{Filename: "/src/work.go", ModuleRelative: "work.go", Package: "example.com/p", Bytes: []byte("package p\nfunc Work() {\n println(1)\n}\n")}
	metrics, err := Analyze(encodedProfile(t, 11, 13, 17), "cpu", []Source{src})
	if err != nil {
		t.Fatal(err)
	}
	m := metrics[0]
	if m.Total != 41 || len(m.Weights) != 2 {
		t.Fatalf("lost samples: %+v", m)
	}
	if m.Weights[0].Flat != 28 || m.Weights[0].Attribution != "exact-source" || m.Weights[1].Flat != 13 || m.Weights[1].Attribution != "unresolved" {
		t.Fatalf("false attribution: %+v", m)
	}
	for _, altered := range []Source{
		{Filename: "/other/work.go", ModuleRelative: "work.go", Package: src.Package, Bytes: src.Bytes},
		{Filename: src.Filename, ModuleRelative: "work.go", Package: src.Package, Bytes: []byte("package p\n//line work.go:2\nfunc Work() {}\n")},
		{Filename: src.Filename, ModuleRelative: "work.go", Package: src.Package, Bytes: []byte("// Code generated by generator. DO NOT EDIT.\npackage p\nfunc Work() {}\n")},
		{Filename: src.Filename, ModuleRelative: "work.go", Package: src.Package, Bytes: []byte("package p\nfunc Other() {\n println(1)\n}\n")},
	} {
		m, err := Analyze(encodedProfile(t, 7), "cpu", []Source{altered})
		if err != nil || m[0].Weights[0].Attribution != "unresolved" {
			t.Fatalf("guessed source: %+v %v", m, err)
		}
	}
}

func TestInlineLeafAndCumulativeOverlap(t *testing.T) {
	inner := &profile.Function{ID: 1, Name: "inline"}
	outer := &profile.Function{ID: 2, Name: "outer"}
	l := &profile.Location{ID: 1, Line: []profile.Line{{Function: inner}, {Function: outer}}}
	p := &profile.Profile{SampleType: []*profile.ValueType{{Type: "cpu", Unit: "nanoseconds"}}, Function: []*profile.Function{inner, outer}, Location: []*profile.Location{l}, Sample: []*profile.Sample{{Location: []*profile.Location{l, l}, Value: []int64{10}}}}
	var b bytes.Buffer
	if err := p.Write(&b); err != nil {
		t.Fatal(err)
	}
	m, err := Analyze(b.Bytes(), "cpu", nil)
	if err != nil {
		t.Fatal(err)
	}
	if m[0].Total != 10 || m[0].Weights[0].Symbol != "inline" || m[0].Weights[0].Flat != 10 || m[0].Weights[1].Flat != 0 || m[0].Weights[1].Cumulative != 10 {
		t.Fatalf("inline weights: %+v", m)
	}
}

func TestProfileRefusesCorruptionNegativeOverflowAndWrongKind(t *testing.T) {
	for _, b := range [][]byte{[]byte("corrupt"), encodedProfile(t, -1), encodedProfile(t, math.MaxInt64, 1)} {
		if _, err := Analyze(b, "cpu", nil); err == nil {
			t.Fatal("invalid samples admitted")
		}
	}
	if _, err := Analyze(encodedProfile(t, 1), "alloc", nil); err == nil {
		t.Fatal("cpu substituted for allocations")
	}
	m, err := Analyze(encodedProfile(t, 0), "cpu", nil)
	if err != nil || !Empty(m) {
		t.Fatalf("zero profile: %v %v", m, err)
	}
}

func FuzzProfileAccounting(f *testing.F) {
	f.Add([]byte{1, 2, 3, 0, 255})
	f.Fuzz(func(t *testing.T, values []byte) {
		var total int64
		v := make([]int64, len(values))
		for i, n := range values {
			v[i] = int64(n)
			total += int64(n)
		}
		metrics, err := Analyze(encodedProfile(t, v...), "cpu", nil)
		if err != nil {
			t.Fatal(err)
		}
		var flat int64
		for _, w := range metrics[0].Weights {
			flat += w.Flat
		}
		if flat != total || metrics[0].Total != total {
			t.Fatalf("flat=%d total=%d want=%d", flat, metrics[0].Total, total)
		}
	})
}

func FuzzProfileAdmission(f *testing.F) {
	f.Add(encodedProfile(f, 5, 8))
	f.Add([]byte("corrupt"))
	f.Fuzz(func(t *testing.T, b []byte) { _, _ = Analyze(b, "cpu", nil) })
}

func FuzzIndexAdmission(f *testing.F) {
	seed, err := Encode(testIndex(f))
	if err != nil {
		f.Fatal(err)
	}
	raw, err := base64.RawURLEncoding.DecodeString(seed)
	if err != nil {
		f.Fatal(err)
	}
	f.Add(string(raw))
	f.Add(`{"version":1,"captures":[]}`)
	f.Add(`{"version":1,"version":1,"captures":[]}`)
	f.Fuzz(func(t *testing.T, raw string) {
		encoded := base64.RawURLEncoding.EncodeToString([]byte(raw))
		if i, err := Decode(encoded); err == nil {
			back, err := Encode(i)
			if err != nil || back != encoded {
				t.Fatalf("noncanonical admitted: %s", raw)
			}
		}
	})
}

func testIndex(t testing.TB) Index {
	t.Helper()
	ledger, err := run.EncodeLedger(run.Ledger{})
	if err != nil {
		t.Fatal(err)
	}
	return Index{Version: 1, Captures: []Capture{{Kind: "cpu", Package: "example.com/p", Benchmark: "BenchmarkX", Selection: "^BenchmarkX$", Children: []Child{{Name: "X", Iterations: 42}}, Budget: "1s", Protocol: Protocol, Scope: Scope, Sampling: "runtime-default", Commit: strings.Repeat("a", 40), Conditions: recordingtest.QuietConditions, BinarySHA256: Digest([]byte("binary")), MeasurementRevision: Digest([]byte("measurement")), Fingerprint: recordingtest.Defaults().Fingerprint, Ledger: ledger, SHA256: Digest([]byte("profile")), Size: 7}}}
}

func TestIndexCanonicalRoundTripAndRefusals(t *testing.T) {
	i := testIndex(t)
	i.Captures[0].Fingerprint.ObservationAssertion = "historical-assertion"
	i.Captures[0].Sources = []Source{{Filename: "/source.go", ModuleRelative: "source.go", Package: "example.com/p", Bytes: []byte(strings.Repeat("// exact source bytes\n", 5000))}}
	encoded, err := Encode(i)
	if err != nil {
		t.Fatal(err)
	}
	got, err := Decode(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if got.Captures[0].Fingerprint != i.Captures[0].Fingerprint || !bytes.Equal(got.Captures[0].Sources[0].Bytes, i.Captures[0].Sources[0].Bytes) {
		t.Fatal("native/source evidence changed")
	}
	rows := recordingtest.Results("X", []float64{1, 2})
	for _, row := range rows {
		row.Config = append(row.Config, run.KeyProfiles.Config(encoded))
	}
	st := store.New(t.TempDir())
	if err := st.Write("", "BenchmarkX", "", rows); err != nil {
		t.Fatal(err)
	}
	stored, err := st.ReadBytes(store.Key{Bench: "BenchmarkX"})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(stored, []byte(run.KeyProfiles.Name+".2: ")) {
		t.Fatal("large profile index was not chunked")
	}
	for _, line := range bytes.Split(stored, []byte{'\n'}) {
		if len(line) >= 64<<10 {
			t.Fatal("oversized benchmark-format line")
		}
	}
	back, err := st.Read("", "BenchmarkX", "")
	if err != nil {
		t.Fatal(err)
	}
	if back[0].GetConfig(run.KeyProfiles.Name) != encoded {
		t.Fatal("chunk round-trip changed index")
	}
	jsonBytes, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil {
		t.Fatal(err)
	}
	for _, broken := range []string{
		strings.Replace(string(jsonBytes), `"version":1`, `"version":1,"version":1`, 1),
		strings.Replace(string(jsonBytes), `"version":1`, `"version":1,"unknown":true`, 1),
		strings.Replace(string(jsonBytes), `"dirty":false,`, "", 1),
		string(jsonBytes) + "{}",
		strings.Replace(string(jsonBytes), `"kind":"cpu"`, `"kind":"heap"`, 1),
	} {
		if _, err := Decode(base64.RawURLEncoding.EncodeToString([]byte(broken))); err == nil {
			t.Fatal("malformed index admitted")
		}
	}
	if _, err := Decode(encoded + "="); err == nil {
		t.Fatal("noncanonical base64 admitted")
	}
	// A canonical unknown/native field cannot be silently ignored on restore.
	var shape map[string]any
	if err := json.Unmarshal(jsonBytes, &shape); err != nil {
		t.Fatal(err)
	}
	shape["captures"].([]any)[0].(map[string]any)["fingerprint"].(map[string]any)["unknown"] = true
	broken, err := json.Marshal(shape)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Decode(base64.RawURLEncoding.EncodeToString(broken)); err == nil {
		t.Fatal("native grammar bypassed")
	}
}

func TestProfileRequestBudgets(t *testing.T) {
	for _, v := range []string{"cpu", "alloc", "cpu,alloc", ""} {
		if _, err := Kinds(v); err != nil {
			t.Fatal(err)
		}
	}
	for _, v := range []string{"CPU", "cpu,cpu", "alloc,cpu", "heap"} {
		if _, err := Kinds(v); err == nil {
			t.Fatal(v)
		}
	}
	for _, v := range []string{"1s", "1ns", "1x"} {
		if err := ValidateBudget(v); err != nil {
			t.Fatal(err)
		}
	}
	for _, v := range []string{"0s", "0x", "-1s", "NaNs", "Inf", strings.Repeat("9", 99) + "x"} {
		if err := ValidateBudget(v); err == nil {
			t.Fatal(v)
		}
	}
}

func TestProfileRelationRejectsMismatchedEvidence(t *testing.T) {
	rows := recordingtest.Results("X", []float64{1})
	fp := recordingtest.Defaults().Fingerprint
	c := Capture{Fingerprint: fp, MeasurementRevision: Revision(rows), Children: []Child{{Name: string(rows[0].Name), Iterations: 1}}}
	if err := Relation(c, rows, fp); err != nil {
		t.Fatal(err)
	}
	for _, change := range []func(*Capture){
		func(c *Capture) { c.MeasurementRevision = Digest([]byte("other revision")) },
		func(c *Capture) { c.Fingerprint.MaximalClosure += "moved" },
		func(c *Capture) { c.Fingerprint.TestVariantClosure += "moved" },
		func(c *Capture) { c.Fingerprint.Guards.BuildConfig += "moved" },
		func(c *Capture) { c.Fingerprint.Guards.RuntimeConfig += "moved" },
		func(c *Capture) { c.Children = []Child{{Name: "Y-8", Iterations: 1}} },
		func(c *Capture) { c.Children = nil },
	} {
		bad := c
		change(&bad)
		if err := Relation(bad, rows, fp); err == nil {
			t.Fatalf("mismatched relation accepted: %+v", bad)
		}
	}
}

func TestProfileRelationRequiresProvenApplicability(t *testing.T) {
	rows := recordingtest.Results("X", []float64{1})
	fp := recordingtest.Defaults().Fingerprint
	c := Capture{Fingerprint: fp, MeasurementRevision: Revision(rows), Children: []Child{{Name: string(rows[0].Name), Iterations: 1}}}
	c.Fingerprint.TestVariantClosure = "current"
	for _, strategy := range []string{gofresh.InertTestVariantExtension, "unknown", ""} {
		fp.InertTestVariantApplicability = gofresh.InertTestVariantApplicability{Strategy: strategy, TestVariantClosure: "current"}
		if err := Relation(c, rows, fp); !errors.Is(err, ErrRelationUnproven) || errors.Is(err, ErrRelationMismatch) {
			t.Fatalf("unproven %q endpoint accepted", strategy)
		}
		if err := CheckedRelation(t.Context(), c, rows, fp, nil); !errors.Is(err, ErrRelationUnproven) || errors.Is(err, ErrRelationMismatch) {
			t.Fatalf("nil view conferred %q applicability", strategy)
		}
	}
}

func TestRelationErrorClasses(t *testing.T) {
	rows := recordingtest.Results("X", []float64{1})
	fp := recordingtest.Defaults().Fingerprint
	fp.InertTestVariantApplicability = gofresh.InertTestVariantApplicability{Strategy: gofresh.InertTestVariantExtension, TestVariantClosure: "current"}
	c := Capture{Fingerprint: fp, MeasurementRevision: Revision(rows), Children: []Child{{Name: string(rows[0].Name), Iterations: 1}}}
	for _, mutate := range []func(*Capture){
		func(c *Capture) { c.MeasurementRevision = "different" },
		func(c *Capture) { c.Children = nil },
		func(c *Capture) { c.Fingerprint.Guards.RuntimeConfig += "different" },
	} {
		bad := c
		mutate(&bad)
		if err := CheckedRelation(t.Context(), bad, rows, fp, nil); !errors.Is(err, ErrRelationMismatch) || errors.Is(err, ErrRelationUnproven) {
			t.Fatalf("pair contradiction masked by missing proof: %v", err)
		}
	}
	unavailable := fmt.Errorf("proof: %w", gofresh.ErrAnalysisUnavailable)
	if err := applicabilityFailure(unavailable); !errors.Is(err, ErrRelationUnproven) || !errors.Is(err, gofresh.ErrAnalysisUnavailable) || errors.Is(err, ErrRelationMismatch) {
		t.Fatalf("unavailable proof misclassified: %v", err)
	}
	for _, err := range []error{context.Canceled, gofresh.ErrViewChanged, errors.New("read failed")} {
		if got := applicabilityFailure(err); got != err || errors.Is(got, ErrRelationUnproven) || errors.Is(got, ErrRelationMismatch) {
			t.Fatalf("operational error misclassified: %v", got)
		}
	}
}
